main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: /research
    weight: 11
  - name: News
    url: /#news
    weight: 12
  # - name: Event
  #   url: /event
  #   weight: 13
  - name: Publication
    url: publication/
    weight: 20
  # - name: Project
  #   url: projects/
  #   weight: 30
  # - name: Teaching
  #   url: teaching/
  #   weight: 40
